### ISSUE TITLE
BloodPuppet/Bending crashes servers

### ISSUE THREAD

**Issue by SoraShiunin** [plushmonkey/JedCore#13]
Latest build as of this date and MC 1.12.2.
BloodBending or BloodPuppet when used on undead mobs(happens more with armored zombies) crashes the server.
Fire comet does not respect worldguard or towny areas, and when bend INTO those areas will blow up blocks that will sometimes fail to regen.

**Comment by plushmonkey** [comment]
I can't replicate any of this. What makes you think it's those that are crashing the server? We have never had any problems with either of them on our server.

FireComet does respect region protection from what I can see. It doesn't when it comes to damage, but it does for destroying blocks. I can fix the damaging aspect.

**Comment by SoraShiunin** [comment]
The default Bloodbending from project korra doesn't crash when used on undead mobs, which makes me think its jedcore only,or maybe some specific code conflicts with some other plugin(using elitemobs and mobcontrol).
FireComet blows up blocks when charged and blasted from an unprotected region into a protected region, can provide a recording/screenshots.

**Comment by SoraShiunin** [comment]
![screenshot_202](https://user-images.githubusercontent.com/23641964/37001403-b274a558-20c6-11e8-95d9-a1681517930d.png)
After updating. Shot a comet from the practice arena to a protected area. This happened.

**Comment by Hetag1216** [comment]
My server's having issues with bloodpuppet enabled as well.
Something with the grab method might be broken / causing the crashes.

**Comment by Hetag1216** [comment]
@SoraShiunin FireComet doesn't have any region issues, every region protection is updated and checked (just tested to be sure).
I guess you're messing up with your region lands, try to redefine your region way better, make it so that has one more block after the wall.

**Comment by SoraShiunin** [comment]
Had bloodpuppet been changed at all since the new releases?

**Comment by SoraShiunin** [comment]
[2020-01-04-14.log](https://github.com/plushmonkey/JedCore/files/4023679/2020-01-04-14.log)
Bloodcrash Still happening in 2020.

**Comment by plushmonkey** [comment]
I just pushed a commit that should fix those issues. They were only happening when IgnoreWalls was set to true, so I could never replicate it before.
