### ISSUE TITLE
Wallrun doesn't do anything.

### ISSUE THREAD

**Issue by soupcant95** [plushmonkey/JedCore#16]
I was excited about the "wallrun" ability, and added it in the config to both air and Chi. It was enabled, but when I came to my server, I coudln't make it work at all. I reloaded, restarted and re-installed the .jar of the plugin, but no luck.

Also, please check my other opened issue.

**Comment by plushmonkey** [comment]
WallRun is a hidden ability, so it doesn't show up in the available abilities list and doesn't have a description.

You can activate it by sprinting, jumping in the air near a wall, and punching toward the open air.

**Comment by soupcant95** [comment]
Is there any way to make it not hidden?
