### ISSUE TITLE
Lost techniques !

### ISSUE THREAD

**Issue by Oogoid35** [plushmonkey/JedCore#18]
I can not find some techniques despite downloading jedcore .some techniques are closed please help

**Comment by plushmonkey** [comment]
I'm not sure what you mean. Could you be more specific?

**Comment by Oogoid35** [comment]
eg Firedragon or Firedisc is not available on my server. I want to know why and how to fix it.

**Comment by plushmonkey** [comment]
Those aren't part of JedCore. You can find other custom abilities on the [ProjectKorra web site](https://projectkorra.com/forum/resources/categories/custom-abilities.3/). You can install those by putting them in the plugins/ProjectKorra/Abilities folder.
