### ISSUE TITLE
Lavaflux,Waterflow and Frostbreath problem

### ISSUE THREAD

**Issue by 0z-zy** [plushmonkey/JedCore#25]
Hi i tried to use them in 1.11.2 but lavaflux doesnt work in it, then used waterflow when you try to make it ice the water stops in the air and if you dont close the frostbreath's snow making configure it doesnt work

**Comment by plushmonkey** [comment]
Sorry about that. Part of 1.12 API was accidentally used, so it broke on older Minecraft versions. I just released a new version that should fix it.

I'm not sure what you mean about FrostBreath. You can open a new issue with more details about it if the latest release doesn't fix it.

**Comment by 0z-zy** [comment]
Lavaflux,waterflow and frostbreath is fixed now thanks
