### ISSUE TITLE
LavaFlux issue 

### ISSUE THREAD

**Issue by Daki1305** [plushmonkey/JedCore#26]
Hey a have issue with LavaFlux ability, i dont know if this is projectkorra bug or jedcore ;p 
![image](https://user-images.githubusercontent.com/42248979/43915485-ba0c3aa8-9c02-11e8-93fc-f162754bc907.png)

**Comment by plushmonkey** [comment]
Sorry about that. Part of 1.12 API was accidentally used, so it broke on older Minecraft versions. I just released a new version that should fix it.
