### ISSUE TITLE
1.13 metalhook issues

### ISSUE THREAD

**Issue by PhanaticD** [plushmonkey/JedCore#29]
metalhook does not function properly, there is an issue with deprecated method once that is fixed you kinda just float https://gyazo.com/088cebf15192e694aa387e1d5ce10671

**Comment by plushmonkey** [comment]
I see the deprecated method issue, but not anything else. It has always functioned pretty poorly like that. Fixing the deprecated method makes it work like it has always worked for me.

Edit: This seems to affect a few abilities that use colored particles. I'd also classify this as more of a wip-1.13 bug.

**Comment by PhanaticD** [comment]
yea i am testing out the wip 1.13 branch
