### ISSUE TITLE
Item Duplication

### ISSUE THREAD

**Issue by ghost** [plushmonkey/JedCore#6]
There is an issue with RegenTempBlock where containers being set to another material drop their contents as well as keep their original contents. I won't go into details on how players can do this, here.

I've fixed this in my fork's branch titled "1.8.6" simply by not proceeding with the method if the block's state is a container; you can either copy and paste it, fix it yourself, or I can submit a pull request.

**Comment by PhanaticD** [comment]
can you explain how its done

**Comment by ghost** [comment]
No, seeing as how a lot of servers may rely on this as a secure/stable plugin. I'm not even sure how far back this issue spans; so it's better to go ahead and patch it now and be more careful in the future. :)

**Comment by SoraShiunin** [comment]
Its by using earthsurf on earthsurfable blocks but with a chest or two underneath and on the way, the contents will drop, infinitely.
This also happens with earthtunnel but thats PK, by mining the block with earthtunnel and then placing another block in that place.

Guess it won't be fixed if noone says how it happens lol.

**Comment by PhanaticD** [comment]
https://github.com/plushmonkey/JedCore/pull/20

**Comment by plushmonkey** [comment]
I tried replicating this issue several times since it was first reported, but it never duplicated for me. I realized today that it's because I use a custom version of ProjectKorra that happens to have a different implementation of TempBlock. I believe the main issue comes from using state reverts in TempBlock.

The patch isn't ideal, but I'll accept it anyway because I'm too lazy to implement anything better.

**Comment by Dooder07** [comment]
I think #20 is fine enough for a long-term solution, it's exactly what I did to fix this issue months ago. I personally couldn't come up with a more efficient and secure way to ignore all in-game containers, myself. Thanks for addressing this.

**Comment by ghost** [comment]
Whoops, commented using the wrong account. lol

Anyways, I feel like #20 is perfectly fine for a long-term solution; it's exactly what I did months ago. When I can get back into this, I will definitely play around with a more efficient fix. I have a couple of ideas..
